from __future__ import annotations

from .config import BuildConfig
from .identity import PRODUCT_NAME
from .manifest import LockGlyph


def _line(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ")


def generate_attribution(glyphs: tuple[LockGlyph, ...], config: BuildConfig) -> bytes:
    documented = tuple(glyph for glyph in glyphs if glyph.metadata)
    lines = [
        "# Icon attribution",
        "",
        f"Generated by {PRODUCT_NAME} from metadata declared in the build config.",
        "The compiler does not verify artwork ownership or license compatibility. Before",
        "shipping, confirm that every source license permits font embedding and subsetting",
        "and preserve any attribution its license requires.",
        "",
        f"Icons in font: {len(glyphs)}",
        f"Icons with declared metadata: {len(documented)}",
        f"Icons without declared metadata: {len(glyphs) - len(documented)}",
    ]
    if config.copyright:
        lines.extend(["", f"Font copyright: {_line(config.copyright)}"])
    for glyph in sorted(documented, key=lambda item: item.source.encode("utf-8")):
        assert glyph.metadata is not None
        lines.extend(["", f"## {glyph.name}", "", f"- Source file: `{glyph.source}`"])
        for key, label in (
            ("author", "Author"),
            ("license", "License"),
            ("sourceUrl", "Upstream source"),
            ("copyright", "Copyright"),
        ):
            value = glyph.metadata.get(key)
            if value:
                lines.append(f"- {label}: {_line(value)}")
    lines.append("")
    return "\n".join(lines).encode("utf-8")
